/* =========================================================
   AI Career Copilot — Static Data
   Career paths, skills taxonomy, IBM SkillsBuild courses
   ========================================================= */

const DATA = {

  /* ----------------------------------------------------------
     SKILLS TAXONOMY
  ---------------------------------------------------------- */
  skillCategories: {
    programming: {
      label: 'Programming Languages',
      skills: ['Python','JavaScript','Java','C++','C#','TypeScript','R','Go','Rust','Kotlin','Swift','PHP','Scala','MATLAB','SQL'],
    },
    webDev: {
      label: 'Web Development',
      skills: ['React','Angular','Vue.js','Node.js','HTML/CSS','REST APIs','GraphQL','Next.js','Django','Flask','Spring Boot','Express.js'],
    },
    dataScience: {
      label: 'Data Science & AI',
      skills: ['Machine Learning','Deep Learning','TensorFlow','PyTorch','Pandas','NumPy','Scikit-learn','Data Visualization','NLP','Computer Vision','MLOps'],
    },
    cloud: {
      label: 'Cloud & DevOps',
      skills: ['AWS','Azure','Google Cloud','Docker','Kubernetes','CI/CD','Terraform','Linux','Git','Jenkins','Ansible'],
    },
    database: {
      label: 'Databases',
      skills: ['MySQL','PostgreSQL','MongoDB','Redis','Elasticsearch','Oracle','SQLite','Cassandra','DynamoDB'],
    },
    softSkills: {
      label: 'Soft Skills',
      skills: ['Communication','Problem Solving','Leadership','Teamwork','Critical Thinking','Time Management','Agile/Scrum','Project Management'],
    },
    security: {
      label: 'Cybersecurity',
      skills: ['Network Security','Penetration Testing','SIEM','Cryptography','Ethical Hacking','OWASP','IAM','SOC Analysis'],
    },
    design: {
      label: 'Design & UX',
      skills: ['UI/UX Design','Figma','Adobe XD','User Research','Wireframing','Accessibility','Design Thinking'],
    },
  },

  /* ----------------------------------------------------------
     CAREER PATHS
  ---------------------------------------------------------- */
  careerPaths: [
    {
      id: 'ai-engineer',
      title: 'AI Engineer',
      emoji: '🧠',
      color: '#6929c4',
      salaryRange: '$120k – $200k',
      demandLevel: 'Very High',
      growth: '+45%',
      description: 'Build and deploy AI-powered applications integrating LLMs, generative AI, and intelligent automation into real-world products at scale.',
      requiredSkills: ['Python','Machine Learning','Deep Learning','TensorFlow','PyTorch','REST APIs','Docker','SQL'],
      niceToHave: ['LangChain','Prompt Engineering','Vector Databases','MLOps','Kubernetes','NLP','Computer Vision'],
      roles: ['AI Developer','AI Engineer','Senior AI Engineer','AI Architect','Head of AI'],
      companies: ['OpenAI','IBM','Google DeepMind','Microsoft','Anthropic','Hugging Face'],
    },
    {
      id: 'data-engineer',
      title: 'Data Engineer',
      emoji: '🏗️',
      color: '#005d5d',
      salaryRange: '$100k – $165k',
      demandLevel: 'Very High',
      growth: '+38%',
      description: 'Design, build and maintain scalable data pipelines and infrastructure that move, transform and store data reliably for analytics and ML.',
      requiredSkills: ['Python','SQL','AWS','Docker','PostgreSQL','Git','Linux'],
      niceToHave: ['Spark','Kafka','Airflow','dbt','Snowflake','Databricks','Terraform','Scala'],
      roles: ['Junior Data Engineer','Data Engineer','Senior Data Engineer','Data Architect','Head of Data'],
      companies: ['Databricks','Snowflake','IBM','Amazon','Uber','Netflix'],
    },
    {
      id: 'mobile-developer',
      title: 'Mobile Developer',
      emoji: '📱',
      color: '#0f62fe',
      salaryRange: '$90k – $150k',
      demandLevel: 'High',
      growth: '+22%',
      description: 'Build native and cross-platform mobile applications for iOS and Android, focusing on performance, seamless UX, and device integration.',
      requiredSkills: ['JavaScript','TypeScript','React','REST APIs','Git','UI/UX Design'],
      niceToHave: ['Swift','Kotlin','React Native','Flutter','Firebase','GraphQL'],
      roles: ['Junior Mobile Dev','Mobile Developer','Senior Mobile Dev','Mobile Architect','Tech Lead'],
      companies: ['Apple','Google','Meta','Spotify','Airbnb','Grab'],
    },
    {
      id: 'blockchain-developer',
      title: 'Blockchain Developer',
      emoji: '⛓️',
      color: '#ff832b',
      salaryRange: '$110k – $180k',
      demandLevel: 'High',
      growth: '+30%',
      description: 'Design and build decentralized applications, smart contracts, and blockchain infrastructure for Web3 and enterprise use cases.',
      requiredSkills: ['JavaScript','Python','Cryptography','REST APIs','Git','SQL'],
      niceToHave: ['Solidity','Rust','Web3.js','Ethereum','Docker','Kubernetes'],
      roles: ['Smart Contract Dev','Blockchain Developer','Senior Blockchain Dev','Web3 Architect','Protocol Engineer'],
      companies: ['Ethereum Foundation','Chainlink','Coinbase','IBM Blockchain','Polygon','Consensys'],
    },
    {
      id: 'game-developer',
      title: 'Game Developer',
      emoji: '🎮',
      color: '#198038',
      salaryRange: '$80k – $140k',
      demandLevel: 'Medium',
      growth: '+15%',
      description: 'Create engaging interactive experiences across platforms using game engines, graphics programming, and gameplay systems design.',
      requiredSkills: ['C++','C#','Python','JavaScript','Git','Problem Solving'],
      niceToHave: ['Unity','Unreal Engine','SQL','Linear Algebra','Physics Simulation','Multiplayer Networking'],
      roles: ['Junior Game Dev','Game Developer','Senior Game Dev','Technical Director','Game Architect'],
      companies: ['Unity','Epic Games','EA','Ubisoft','CD Projekt Red','Riot Games'],
    },
    {
      id: 'data-scientist',
      title: 'Data Scientist',
      emoji: '🔬',
      color: '#6929c4',
      salaryRange: '$90k – $150k',
      demandLevel: 'Very High',
      growth: '+36%',
      description: 'Analyze complex data sets, build predictive models, and extract actionable insights using statistical and ML techniques.',
      requiredSkills: ['Python','SQL','Machine Learning','Statistics','Data Visualization','Pandas','NumPy','TensorFlow'],
      niceToHave: ['Deep Learning','NLP','Spark','Tableau','Power BI'],
      roles: ['Junior Data Analyst','Data Analyst','Senior Data Scientist','Lead Data Scientist','Principal Scientist'],
      companies: ['IBM','Google','Meta','Amazon','Microsoft','Airbnb'],
    },
    {
      id: 'ml-engineer',
      title: 'ML Engineer',
      emoji: '🤖',
      color: '#0f62fe',
      salaryRange: '$110k – $175k',
      demandLevel: 'Very High',
      growth: '+40%',
      description: 'Design, build and deploy machine learning systems and pipelines at scale in production environments.',
      requiredSkills: ['Python','Machine Learning','Docker','Kubernetes','TensorFlow','PyTorch','CI/CD','SQL'],
      niceToHave: ['Scala','Spark','MLOps','AWS Sagemaker','Kubeflow'],
      roles: ['Junior ML Engineer','ML Engineer','Senior ML Engineer','ML Architect','AI Tech Lead'],
      companies: ['IBM','OpenAI','DeepMind','Tesla','Nvidia','Databricks'],
    },
    {
      id: 'full-stack-dev',
      title: 'Full Stack Developer',
      emoji: '💻',
      color: '#007d79',
      salaryRange: '$85k – $140k',
      demandLevel: 'High',
      growth: '+25%',
      description: 'Build end-to-end web applications covering both client-side and server-side code, databases, and APIs.',
      requiredSkills: ['JavaScript','React','Node.js','HTML/CSS','REST APIs','SQL','Git'],
      niceToHave: ['TypeScript','GraphQL','Docker','AWS','Next.js','MongoDB'],
      roles: ['Frontend Dev','Backend Dev','Full Stack Dev','Senior Dev','Tech Lead','CTO'],
      companies: ['Startup','Accenture','TCS','Infosys','Amazon','Shopify'],
    },
    {
      id: 'cloud-architect',
      title: 'Cloud Architect',
      emoji: '☁️',
      color: '#0043ce',
      salaryRange: '$130k – $200k',
      demandLevel: 'High',
      growth: '+28%',
      description: 'Design and oversee cloud computing strategy including adoption plans, cloud application design, and cloud management.',
      requiredSkills: ['AWS','Azure','Google Cloud','Kubernetes','Docker','Terraform','Networking','Linux'],
      niceToHave: ['Security','Cost Optimization','Multi-cloud','ServiceMesh','Istio'],
      roles: ['Cloud Engineer','Senior Cloud Engineer','Cloud Architect','Principal Architect','VP of Infrastructure'],
      companies: ['IBM','Accenture','Deloitte','AWS','Microsoft','Google'],
    },
    {
      id: 'cybersecurity',
      title: 'Cybersecurity Analyst',
      emoji: '🔐',
      color: '#da1e28',
      salaryRange: '$85k – $145k',
      demandLevel: 'Very High',
      growth: '+35%',
      description: 'Protect organizations from digital attacks by monitoring, detecting, investigating, analyzing and responding to security events.',
      requiredSkills: ['Network Security','SIEM','Linux','Ethical Hacking','Cryptography','Python','OWASP'],
      niceToHave: ['Penetration Testing','IAM','SOC Analysis','Cloud Security','Forensics'],
      roles: ['SOC Analyst','Security Analyst','Pen Tester','Security Engineer','CISO'],
      companies: ['IBM Security','CrowdStrike','Palo Alto Networks','FireEye','Cisco'],
    },
    {
      id: 'devops-engineer',
      title: 'DevOps Engineer',
      emoji: '⚙️',
      color: '#ff832b',
      salaryRange: '$95k – $155k',
      demandLevel: 'High',
      growth: '+22%',
      description: 'Bridge development and operations through automation, CI/CD pipelines, infrastructure as code, and system reliability.',
      requiredSkills: ['Docker','Kubernetes','CI/CD','Linux','Git','Jenkins','Python','AWS'],
      niceToHave: ['Terraform','Ansible','Prometheus','Grafana','SRE practices'],
      roles: ['Junior DevOps','DevOps Engineer','SRE','Platform Engineer','Infrastructure Lead'],
      companies: ['IBM','GitLab','HashiCorp','Netflix','Spotify','Uber'],
    },
    {
      id: 'ux-designer',
      title: 'UX/UI Designer',
      emoji: '🎨',
      color: '#e5a800',
      salaryRange: '$75k – $120k',
      demandLevel: 'Medium',
      growth: '+16%',
      description: 'Create intuitive, accessible and beautiful digital experiences through research, prototyping, and design systems.',
      requiredSkills: ['Figma','User Research','Wireframing','Design Thinking','Accessibility','HTML/CSS'],
      niceToHave: ['Adobe XD','Principle','React','Design Systems','Animation'],
      roles: ['UX Researcher','UI Designer','UX Designer','Senior Designer','Design Lead','Head of Design'],
      companies: ['IBM iX','IDEO','Frog Design','Apple','Google','Airbnb'],
    },
    {
      id: 'product-manager',
      title: 'Product Manager',
      emoji: '📋',
      color: '#198038',
      salaryRange: '$95k – $160k',
      demandLevel: 'High',
      growth: '+19%',
      description: 'Define product vision, prioritize features, and coordinate cross-functional teams to ship products that solve user problems.',
      requiredSkills: ['Product Strategy','Agile/Scrum','Data Analysis','Communication','Leadership','User Research','SQL'],
      niceToHave: ['A/B Testing','Roadmapping','Python','Figma','Market Research'],
      roles: ['Associate PM','Product Manager','Senior PM','Group PM','Director of Product','CPO'],
      companies: ['IBM','Google','Amazon','Meta','Stripe','Atlassian'],
    },
  ],

  /* ----------------------------------------------------------
     IBM SKILLSBUILD COURSES
  ---------------------------------------------------------- */
  courses: [
    // AI & Machine Learning
    {
      id: 'c001',
      title: 'Introduction to Artificial Intelligence',
      provider: 'IBM SkillsBuild',
      category: 'ai',
      level: 'Beginner',
      duration: '6 hours',
      rating: 4.8,
      enrolled: '120K+',
      skills: ['Machine Learning','AI Fundamentals','Python'],
      description: 'Explore AI concepts, applications and ethics. Learn about machine learning, deep learning and natural language processing.',
      color: '#6929c4',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'AI Foundations',
      careers: ['data-scientist','ml-engineer'],
    },
    {
      id: 'c002',
      title: 'Machine Learning with Python',
      provider: 'IBM SkillsBuild',
      category: 'ai',
      level: 'Intermediate',
      duration: '12 hours',
      rating: 4.9,
      enrolled: '85K+',
      skills: ['Python','Machine Learning','Scikit-learn','Pandas'],
      description: 'Build and evaluate machine learning models using Python, scikit-learn, and real-world datasets.',
      color: '#0f62fe',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'ML Practitioner',
      careers: ['data-scientist','ml-engineer'],
    },
    {
      id: 'c003',
      title: 'Deep Learning with TensorFlow',
      provider: 'IBM SkillsBuild',
      category: 'ai',
      level: 'Advanced',
      duration: '18 hours',
      rating: 4.7,
      enrolled: '45K+',
      skills: ['TensorFlow','Deep Learning','Python','Neural Networks'],
      description: 'Design, train and deploy neural networks using TensorFlow and Keras for real-world AI applications.',
      color: '#da1e28',
      free: false,
      url: 'https://skillsbuild.org',
      badge: 'Deep Learning Expert',
      careers: ['ml-engineer','data-scientist'],
    },
    // Cloud
    {
      id: 'c004',
      title: 'Cloud Computing Fundamentals',
      provider: 'IBM SkillsBuild',
      category: 'cloud',
      level: 'Beginner',
      duration: '8 hours',
      rating: 4.6,
      enrolled: '200K+',
      skills: ['AWS','Azure','Google Cloud','Cloud Basics'],
      description: 'Understand the core concepts of cloud computing, deployment models, and major cloud providers.',
      color: '#0043ce',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Cloud Foundations',
      careers: ['cloud-architect','devops-engineer'],
    },
    {
      id: 'c005',
      title: 'IBM Cloud Practitioner Essentials',
      provider: 'IBM SkillsBuild',
      category: 'cloud',
      level: 'Beginner',
      duration: '10 hours',
      rating: 4.7,
      enrolled: '75K+',
      skills: ['IBM Cloud','Docker','Kubernetes','CI/CD'],
      description: 'Master IBM Cloud services, container orchestration, and modern DevOps practices.',
      color: '#0f62fe',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'IBM Cloud Essentials',
      careers: ['cloud-architect','devops-engineer'],
    },
    {
      id: 'c016',
      title: 'Generative AI Fundamentals',
      provider: 'IBM SkillsBuild',
      category: 'ai',
      level: 'Beginner',
      duration: '6 hours',
      rating: 4.9,
      enrolled: '95K+',
      skills: ['Machine Learning','Deep Learning','Python','NLP'],
      description: 'Explore generative AI concepts, LLMs, prompt engineering, and how to build AI-powered applications responsibly.',
      color: '#6929c4',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Generative AI Essentials',
      careers: ['ai-engineer','ml-engineer','data-scientist'],
    },
    {
      id: 'c017',
      title: 'Data Engineering with Apache Spark',
      provider: 'IBM SkillsBuild',
      category: 'data',
      level: 'Intermediate',
      duration: '16 hours',
      rating: 4.7,
      enrolled: '42K+',
      skills: ['Python','SQL','AWS','Docker','PostgreSQL'],
      description: 'Build robust data pipelines with Apache Spark, process large datasets, and integrate with cloud storage and data lakes.',
      color: '#005d5d',
      free: false,
      url: 'https://skillsbuild.org',
      badge: 'Data Engineer',
      careers: ['data-engineer','data-scientist'],
    },
    {
      id: 'c018',
      title: 'Mobile App Development with React Native',
      provider: 'IBM SkillsBuild',
      category: 'development',
      level: 'Intermediate',
      duration: '14 hours',
      rating: 4.6,
      enrolled: '33K+',
      skills: ['JavaScript','TypeScript','React','REST APIs'],
      description: 'Build cross-platform iOS and Android apps with React Native — covering navigation, state management, and device APIs.',
      color: '#0f62fe',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Mobile Developer',
      careers: ['mobile-developer','full-stack-dev'],
    },
    {
      id: 'c019',
      title: 'Blockchain Essentials',
      provider: 'IBM SkillsBuild',
      category: 'blockchain',
      level: 'Beginner',
      duration: '8 hours',
      rating: 4.5,
      enrolled: '28K+',
      skills: ['Cryptography','JavaScript','Python'],
      description: 'Understand blockchain fundamentals, distributed ledgers, consensus mechanisms, and IBM Hyperledger enterprise use cases.',
      color: '#ff832b',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Blockchain Essentials',
      careers: ['blockchain-developer'],
    },
    {
      id: 'c020',
      title: 'Game Development with Unity',
      provider: 'IBM SkillsBuild',
      category: 'development',
      level: 'Beginner',
      duration: '12 hours',
      rating: 4.6,
      enrolled: '19K+',
      skills: ['C#','C++','JavaScript','Problem Solving'],
      description: 'Create 2D and 3D games using Unity Engine — covering game physics, scripting in C#, UI systems, and publishing to multiple platforms.',
      color: '#198038',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Unity Developer',
      careers: ['game-developer'],
    },
    {
      id: 'c006',
      title: 'Kubernetes and Container Orchestration',
      provider: 'IBM SkillsBuild',
      category: 'cloud',
      level: 'Intermediate',
      duration: '14 hours',
      rating: 4.8,
      enrolled: '38K+',
      skills: ['Kubernetes','Docker','DevOps','CI/CD'],
      description: 'Deploy, scale, and manage containerized applications using Kubernetes on any cloud platform.',
      color: '#007d79',
      free: false,
      url: 'https://skillsbuild.org',
      badge: 'Kubernetes Administrator',
      careers: ['devops-engineer','cloud-architect','ml-engineer'],
    },
    // Data
    {
      id: 'c007',
      title: 'Data Science Foundations',
      provider: 'IBM SkillsBuild',
      category: 'data',
      level: 'Beginner',
      duration: '10 hours',
      rating: 4.8,
      enrolled: '150K+',
      skills: ['Python','SQL','Data Analysis','Statistics'],
      description: 'Learn the fundamentals of data science: data exploration, visualization, and statistical analysis.',
      color: '#6929c4',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Data Science Foundations',
      careers: ['data-scientist'],
    },
    {
      id: 'c008',
      title: 'SQL and Database Essentials',
      provider: 'IBM SkillsBuild',
      category: 'data',
      level: 'Beginner',
      duration: '7 hours',
      rating: 4.5,
      enrolled: '110K+',
      skills: ['SQL','MySQL','PostgreSQL','Database Design'],
      description: 'Write complex SQL queries, design relational databases, and manage data effectively.',
      color: '#198038',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'SQL Fundamentals',
      careers: ['data-scientist','full-stack-dev','product-manager'],
    },
    // Cybersecurity
    {
      id: 'c009',
      title: 'Cybersecurity Fundamentals',
      provider: 'IBM SkillsBuild',
      category: 'security',
      level: 'Beginner',
      duration: '9 hours',
      rating: 4.7,
      enrolled: '95K+',
      skills: ['Network Security','Cryptography','Ethical Hacking','OWASP'],
      description: 'Learn the core principles of cybersecurity, threat modeling, and security best practices.',
      color: '#da1e28',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Cybersecurity Fundamentals',
      careers: ['cybersecurity'],
    },
    {
      id: 'c010',
      title: 'IBM Security QRadar SIEM',
      provider: 'IBM SkillsBuild',
      category: 'security',
      level: 'Intermediate',
      duration: '16 hours',
      rating: 4.6,
      enrolled: '22K+',
      skills: ['SIEM','SOC Analysis','Network Security','Threat Detection'],
      description: 'Master IBM QRadar for security intelligence, threat detection, and incident response.',
      color: '#750e13',
      free: false,
      url: 'https://skillsbuild.org',
      badge: 'QRadar Analyst',
      careers: ['cybersecurity'],
    },
    // Development
    {
      id: 'c011',
      title: 'Full Stack JavaScript Development',
      provider: 'IBM SkillsBuild',
      category: 'development',
      level: 'Intermediate',
      duration: '20 hours',
      rating: 4.7,
      enrolled: '60K+',
      skills: ['JavaScript','React','Node.js','REST APIs','MongoDB'],
      description: 'Build complete web applications with React, Node.js, Express, and MongoDB from scratch.',
      color: '#007d79',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Full Stack Developer',
      careers: ['full-stack-dev'],
    },
    {
      id: 'c012',
      title: 'Python for Everybody',
      provider: 'IBM SkillsBuild',
      category: 'development',
      level: 'Beginner',
      duration: '8 hours',
      rating: 4.9,
      enrolled: '300K+',
      skills: ['Python','Programming Fundamentals','Data Structures'],
      description: 'Start your programming journey with Python — the most versatile and in-demand language in tech.',
      color: '#0f62fe',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Python Essentials',
      careers: ['data-scientist','ml-engineer','full-stack-dev','devops-engineer'],
    },
    // Design
    {
      id: 'c013',
      title: 'Enterprise Design Thinking',
      provider: 'IBM SkillsBuild',
      category: 'design',
      level: 'Beginner',
      duration: '5 hours',
      rating: 4.8,
      enrolled: '500K+',
      skills: ['Design Thinking','User Research','Problem Solving','Prototyping'],
      description: "Apply IBM's Enterprise Design Thinking framework to solve complex problems in teams.",
      color: '#e5a800',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Design Thinker',
      careers: ['ux-designer','product-manager'],
    },
    {
      id: 'c014',
      title: 'Agile Explorer',
      provider: 'IBM SkillsBuild',
      category: 'methodology',
      level: 'Beginner',
      duration: '4 hours',
      rating: 4.6,
      enrolled: '180K+',
      skills: ['Agile/Scrum','Project Management','Teamwork'],
      description: 'Understand agile principles and practices to deliver better products faster with cross-functional teams.',
      color: '#198038',
      free: true,
      url: 'https://skillsbuild.org',
      badge: 'Agile Explorer',
      careers: ['product-manager','full-stack-dev','devops-engineer'],
    },
    {
      id: 'c015',
      title: 'Natural Language Processing with Transformers',
      provider: 'IBM SkillsBuild',
      category: 'ai',
      level: 'Advanced',
      duration: '22 hours',
      rating: 4.8,
      enrolled: '28K+',
      skills: ['NLP','Python','TensorFlow','Deep Learning','BERT'],
      description: 'Build state-of-the-art NLP applications with transformer models like BERT, GPT, and T5.',
      color: '#6929c4',
      free: false,
      url: 'https://skillsbuild.org',
      badge: 'NLP Specialist',
      careers: ['ml-engineer','data-scientist'],
    },
  ],

  /* ----------------------------------------------------------
     MOCK INTERVIEW QUESTIONS
  ---------------------------------------------------------- */
  interviewQuestions: {
    'data-scientist': [
      { q: 'Explain the difference between supervised and unsupervised learning. Give examples of each.', difficulty: 'Easy', topic: 'ML Fundamentals', tips: 'Start with clear definitions, then provide concrete real-world examples like email spam classification for supervised and customer segmentation for unsupervised.' },
      { q: 'What is overfitting, and how would you prevent it in a machine learning model?', difficulty: 'Medium', topic: 'Model Evaluation', tips: 'Mention techniques like cross-validation, regularization (L1/L2), dropout, pruning, and early stopping. Explain the bias-variance tradeoff.' },
      { q: 'Walk me through how you would approach a new data science project from problem definition to deployment.', difficulty: 'Hard', topic: 'Project Lifecycle', tips: 'Cover: business problem → data collection → EDA → feature engineering → model selection → evaluation → deployment → monitoring.' },
      { q: 'How would you handle missing data in a dataset? What are the tradeoffs of each approach?', difficulty: 'Medium', topic: 'Data Preprocessing', tips: 'Discuss deletion, mean/median/mode imputation, KNN imputation, and model-based imputation. Discuss when each is appropriate.' },
      { q: 'Explain the ROC curve and AUC metric. When is it useful and when might it be misleading?', difficulty: 'Medium', topic: 'Model Evaluation', tips: 'Explain True Positive Rate vs False Positive Rate, AUC interpretation. Mention class imbalance as a caveat where precision-recall curve might be better.' },
    ],
    'ml-engineer': [
      { q: 'How would you design a scalable ML pipeline for real-time predictions serving 10 million users per day?', difficulty: 'Hard', topic: 'System Design', tips: 'Discuss feature stores, model serving frameworks (TF Serving, Triton), caching strategies, horizontal scaling, and monitoring.' },
      { q: 'Explain the concept of model drift and how you would monitor and address it in production.', difficulty: 'Hard', topic: 'MLOps', tips: 'Cover data drift, concept drift, and model performance drift. Mention statistical tests, automated retraining pipelines, and alerting.' },
      { q: "What are the tradeoffs between batch inference and real-time inference? When would you choose each?", difficulty: 'Medium', topic: 'Inference', tips: 'Batch: cost-efficient, high throughput, latency tolerant. Real-time: low latency, interactive use cases. Discuss examples.' },
      { q: 'How would you reduce the inference latency of a deep learning model in production?', difficulty: 'Hard', topic: 'Optimization', tips: 'Model quantization, pruning, knowledge distillation, TensorRT, ONNX, efficient architectures, caching predictions, hardware acceleration.' },
      { q: 'Describe your approach to A/B testing a new ML model before full deployment.', difficulty: 'Medium', topic: 'Deployment', tips: 'Shadow mode testing, canary deployments, champion-challenger setup, statistical significance, business metrics vs ML metrics.' },
    ],
    'full-stack-dev': [
      { q: 'Explain the difference between REST and GraphQL APIs. When would you prefer one over the other?', difficulty: 'Medium', topic: 'APIs', tips: 'REST: simple, cacheable, widely supported. GraphQL: flexible querying, reduces over/under-fetching. Discuss scenarios for each.' },
      { q: 'How does the JavaScript event loop work? Explain with an example involving async/await.', difficulty: 'Hard', topic: 'JavaScript', tips: 'Explain call stack, Web APIs, callback queue, microtask queue. Trace through a Promise-based async/await example.' },
      { q: 'What are React hooks? Explain useState, useEffect and useContext with use cases.', difficulty: 'Medium', topic: 'React', tips: 'Cover their purpose, rules of hooks, dependency arrays in useEffect, and avoid over-using context vs state management libraries.' },
      { q: 'Describe strategies you would use to optimize the performance of a slow web application.', difficulty: 'Hard', topic: 'Performance', tips: 'Code splitting, lazy loading, memoization, CDN, caching, database query optimization, pagination, image optimization, Lighthouse audits.' },
      { q: 'How would you implement authentication and authorization in a full-stack application?', difficulty: 'Medium', topic: 'Security', tips: 'JWT vs sessions, OAuth2/OIDC, bcrypt for passwords, HTTPS, CORS, RBAC for authorization, refresh token rotation.' },
    ],
    'cloud-architect': [
      { q: 'Design a highly available, fault-tolerant architecture for a global e-commerce platform on AWS/Azure.', difficulty: 'Hard', topic: 'Architecture', tips: 'Multi-region, auto-scaling groups, load balancers, CDN, RDS Multi-AZ, Redis for caching, SQS for async processing, Route 53.' },
      { q: 'Explain the differences between IaaS, PaaS, and SaaS with real-world cloud service examples.', difficulty: 'Easy', topic: 'Cloud Basics', tips: 'IaaS: EC2/VMs. PaaS: Elastic Beanstalk/App Service. SaaS: Salesforce/Gmail. Discuss responsibility models.' },
      { q: 'How would you approach migrating a monolithic on-premise application to the cloud?', difficulty: 'Hard', topic: 'Migration', tips: '6 Rs framework: Rehost, Replatform, Refactor, Repurchase, Retire, Retain. Assess dependencies, data, compliance, downtime tolerance.' },
      { q: 'What strategies would you use to optimize cloud costs without compromising performance?', difficulty: 'Medium', topic: 'Cost Optimization', tips: 'Reserved instances, spot instances, auto-scaling, right-sizing, S3 lifecycle policies, data transfer optimization, tagging.' },
    ],
    'cybersecurity': [
      { q: 'You receive an alert that a server is beaconing to an external IP at regular intervals. Walk me through your incident response process.', difficulty: 'Hard', topic: 'Incident Response', tips: 'Detection → containment → investigation (netflow, process list, persistence mechanisms) → eradication → recovery → lessons learned.' },
      { q: 'Explain the OWASP Top 10 and describe how you would remediate SQL injection vulnerabilities.', difficulty: 'Medium', topic: 'Application Security', tips: 'List OWASP Top 10, deep-dive SQL injection: parameterized queries, ORMs, input validation, WAF, least-privilege DB accounts.' },
      { q: 'What is zero trust architecture and how does it differ from traditional perimeter-based security?', difficulty: 'Medium', topic: 'Architecture', tips: '"Never trust, always verify." Identity-centric, micro-segmentation, continuous verification, least privilege. Compare to castle-moat model.' },
      { q: 'How does asymmetric encryption work and where is it used in TLS handshakes?', difficulty: 'Medium', topic: 'Cryptography', tips: 'Public/private key pairs, RSA/ECC, digital signatures. TLS: key exchange uses asymmetric, bulk data uses symmetric (AES). Certificate chain.' },
    ],
    'devops-engineer': [
      { q: 'Walk me through how you would design a CI/CD pipeline for a microservices application.', difficulty: 'Hard', topic: 'CI/CD', tips: 'Source → build → test (unit, integration, security scan) → containerize → push to registry → deploy to staging → smoke test → production.' },
      { q: 'Explain the difference between blue-green and canary deployments. When would you use each?', difficulty: 'Medium', topic: 'Deployment', tips: 'Blue-green: instant swap, full capacity, easy rollback. Canary: gradual traffic shift, real user validation. Cost and risk tradeoffs.' },
      { q: 'Your application has been experiencing intermittent latency spikes in production. How would you diagnose this?', difficulty: 'Hard', topic: 'Observability', tips: 'USE/RED method, distributed tracing (Jaeger/Zipkin), metrics (Prometheus), logs (ELK), profiling, network analysis, database slow queries.' },
      { q: 'How would you implement infrastructure as code for a multi-environment setup (dev/staging/prod)?', difficulty: 'Medium', topic: 'IaC', tips: 'Terraform workspaces or separate states, variable files per env, DRY modules, remote state in S3 with locking, plan before apply.' },
    ],
    'ux-designer': [
      { q: 'Walk me through your UX design process for a new feature from user research to final design.', difficulty: 'Medium', topic: 'Design Process', tips: 'Define problem → user research (interviews, surveys) → personas → user journeys → wireframes → prototyping → usability testing → iterate.' },
      { q: 'How do you balance business requirements with user needs when they conflict?', difficulty: 'Hard', topic: 'Strategy', tips: 'Data-driven argumentation, A/B testing, user quotes, business metrics tied to UX, negotiation, MVP approach.' },
      { q: 'Explain the principles of accessible design and how you would audit a product for WCAG compliance.', difficulty: 'Medium', topic: 'Accessibility', tips: 'WCAG 2.1 A/AA/AAA. POUR principles: Perceivable, Operable, Understandable, Robust. Tools: axe, Lighthouse, screen reader testing.' },
      { q: 'How would you measure whether a redesign improved the user experience?', difficulty: 'Medium', topic: 'UX Metrics', tips: 'HEART framework (Happiness, Engagement, Adoption, Retention, Task Success), NPS, task completion rate, time-on-task, SUS score.' },
    ],
    'product-manager': [
      { q: "How would you prioritize features on a product roadmap when you have limited engineering resources?", difficulty: 'Hard', topic: 'Prioritization', tips: 'RICE, MoSCoW, ICE, Kano model. Balance user value, business impact, effort. Stakeholder alignment. OKR-driven prioritization.' },
      { q: 'Tell me about a time you used data to make a product decision. What was the outcome?', difficulty: 'Medium', topic: 'Data-Driven PM', tips: 'STAR format. Mention specific metrics, analysis, hypothesis, decision, and measured outcome. Be honest about what you learned.' },
      { q: "Describe how you would write a product requirements document (PRD) for a new AI feature.", difficulty: 'Medium', topic: 'Documentation', tips: 'Problem statement, user personas, success metrics, user stories, requirements (functional + non-functional), edge cases, out-of-scope.' },
      { q: 'How do you ensure alignment between product, engineering, design, and business stakeholders?', difficulty: 'Hard', topic: 'Stakeholder Management', tips: 'Regular syncs, shared OKRs, transparent roadmaps, async communication, RACI matrix, retrospectives, decision logs.' },
    ],

    'ai-engineer': [
      { q: 'Explain the difference between a traditional ML model and a large language model (LLM). When would you use each?', difficulty: 'Medium', topic: 'AI Fundamentals', tips: 'ML models: task-specific, structured data, interpretable. LLMs: general-purpose, unstructured text, emergent capabilities. Discuss cost, latency, and fine-tuning tradeoffs.' },
      { q: 'How would you design a RAG (Retrieval-Augmented Generation) system for a company knowledge base?', difficulty: 'Hard', topic: 'System Design', tips: 'Cover: document ingestion → chunking → embedding → vector store → retrieval → prompt construction → LLM response. Mention reranking, eval metrics, and hallucination mitigation.' },
      { q: 'What are the main challenges of deploying LLMs in production and how would you address them?', difficulty: 'Hard', topic: 'MLOps', tips: 'Latency, cost, hallucinations, prompt injection, context limits, model versioning, monitoring. Discuss caching, streaming, guardrails, and evals.' },
      { q: 'Explain prompt engineering techniques: zero-shot, few-shot, chain-of-thought, and ReAct.', difficulty: 'Medium', topic: 'Prompt Engineering', tips: 'Define each with examples. Chain-of-thought improves reasoning on complex tasks. ReAct enables tool use (Reason + Act). Mention token cost tradeoffs.' },
      { q: 'How would you evaluate the quality of an AI application that uses an LLM as its core component?', difficulty: 'Hard', topic: 'Evaluation', tips: 'RAGAS for RAG pipelines, LLM-as-judge, human eval, task-specific metrics. Discuss ground truth creation, regression testing, and safety evals.' },
    ],
    'data-engineer': [
      { q: 'Explain the difference between a data warehouse, a data lake, and a data lakehouse.', difficulty: 'Medium', topic: 'Data Architecture', tips: 'Warehouse: structured, SQL, high cost. Lake: raw, schema-on-read, cheap. Lakehouse: combines both (Delta Lake, Iceberg). Discuss query performance and use cases.' },
      { q: 'How would you design a data pipeline that processes 10 TB of data daily with sub-hour latency?', difficulty: 'Hard', topic: 'System Design', tips: 'Batch vs micro-batch vs streaming. Spark for batch, Kafka + Flink for streaming. Partitioning, parallelism, checkpointing, idempotency, monitoring.' },
      { q: 'What is data lineage and why is it important? How would you implement it?', difficulty: 'Medium', topic: 'Data Quality', tips: 'Tracking data origin, transformations, and destinations. Tools: Apache Atlas, OpenLineage, dbt. Regulatory compliance, debugging failures, impact analysis.' },
      { q: 'Explain the concept of idempotency in data pipelines. How do you ensure exactly-once processing?', difficulty: 'Hard', topic: 'Pipeline Design', tips: 'Idempotent operations produce the same result regardless of retries. Deduplication keys, upserts, watermarking in streaming, transactional writes.' },
      { q: 'How would you handle schema evolution in a data pipeline without breaking downstream consumers?', difficulty: 'Medium', topic: 'Schema Management', tips: 'Schema registry (Confluent), backward/forward compatibility, Avro/Protobuf, versioned datasets, contract testing, feature flags for migrations.' },
    ],
    'mobile-developer': [
      { q: 'Explain the differences between React Native and Flutter. When would you choose one over the other?', difficulty: 'Medium', topic: 'Frameworks', tips: 'React Native: JS bridge, larger ecosystem, code sharing with web. Flutter: Dart, compiled to native, consistent UI. Discuss performance, team skills, and platform-specific needs.' },
      { q: 'How does state management work in a React Native app? Compare Context API, Redux, and Zustand.', difficulty: 'Medium', topic: 'State Management', tips: 'Context: simple, no boilerplate. Redux: predictable, time-travel debugging, verbose. Zustand: lightweight, minimal. Discuss when global state is warranted vs local.' },
      { q: 'What strategies would you use to optimize the performance of a slow mobile app?', difficulty: 'Hard', topic: 'Performance', tips: 'FlatList virtualization, memoization (React.memo, useMemo), reducing re-renders, image caching, lazy loading, Hermes JS engine, Flipper profiling.' },
      { q: 'How would you implement offline support in a mobile application?', difficulty: 'Hard', topic: 'Offline First', tips: 'Local storage (AsyncStorage, SQLite, MMKV), sync strategies (optimistic updates, conflict resolution), background sync, network detection, queue pending operations.' },
      { q: 'Describe best practices for securing sensitive data in a mobile application.', difficulty: 'Medium', topic: 'Security', tips: 'Keychain/Keystore for secrets, certificate pinning, biometric auth, encrypted storage, obfuscation, no hardcoded credentials, secure API communication.' },
    ],
    'blockchain-developer': [
      { q: 'Explain how a blockchain achieves consensus. Compare Proof of Work and Proof of Stake.', difficulty: 'Medium', topic: 'Blockchain Fundamentals', tips: 'PoW: computational puzzle, energy intensive, Sybil resistant. PoS: stake-based validator selection, energy efficient. Discuss finality, decentralization tradeoffs, and examples.' },
      { q: 'What are smart contracts? What are their limitations and common security vulnerabilities?', difficulty: 'Medium', topic: 'Smart Contracts', tips: 'Self-executing code on-chain. Limitations: no external data (oracle problem), immutability, gas costs. Vulnerabilities: reentrancy, integer overflow, front-running, access control.' },
      { q: 'How does a DeFi protocol manage liquidity? Explain Automated Market Makers (AMMs).', difficulty: 'Hard', topic: 'DeFi', tips: 'AMMs use liquidity pools and bonding curves (x*y=k) instead of order books. Liquidity providers earn fees. Discuss impermanent loss, slippage, and capital efficiency.' },
      { q: 'How would you design a secure NFT minting contract with a whitelist and reveal mechanism?', difficulty: 'Hard', topic: 'Smart Contract Design', tips: 'Merkle tree for whitelist, Chainlink VRF for randomness, metadata reveal pattern, ERC-721A for gas efficiency, reentrancy guards, access control roles.' },
      { q: 'What is the oracle problem in blockchain and how does Chainlink solve it?', difficulty: 'Medium', topic: 'Oracles', tips: 'Blockchains cannot access external data natively. Chainlink: decentralized oracle network, multiple data sources, reputation system, cryptographic proofs.' },
    ],
    'game-developer': [
      { q: 'Explain the game loop. How does fixed vs variable timestep affect game physics and rendering?', difficulty: 'Medium', topic: 'Game Architecture', tips: 'Game loop: input → update → render. Fixed timestep: deterministic physics, requires interpolation. Variable: smooth rendering but non-deterministic. Semi-fixed is best of both.' },
      { q: 'How would you design an Entity Component System (ECS) architecture for a game?', difficulty: 'Hard', topic: 'Architecture', tips: 'Entities: IDs only. Components: pure data. Systems: logic that processes components. Benefits: cache-friendly, composable, decoupled. Compare to OOP inheritance.' },
      { q: 'What are the common causes of frame rate drops in a game and how would you profile and fix them?', difficulty: 'Hard', topic: 'Performance', tips: 'CPU-bound (AI, physics), GPU-bound (overdraw, fillrate), memory allocation/GC. Tools: Unity Profiler, Unreal Insights, RenderDoc. Batching, LOD, culling, object pooling.' },
      { q: 'Explain how you would implement a pathfinding system for an RTS game with thousands of units.', difficulty: 'Hard', topic: 'AI & Algorithms', tips: 'A* for individual paths, flow fields for crowd movement, navmesh for terrain. Hierarchical pathfinding (HPA*) for scale. Spatial hashing, multithreading, local avoidance (RVO).' },
      { q: 'How does multiplayer networking work in a real-time game? Explain client-side prediction and server reconciliation.', difficulty: 'Hard', topic: 'Networking', tips: 'Client predicts locally, server is authoritative. Reconcile by replaying inputs after server correction. Lag compensation, interpolation, dead reckoning for smooth experience.' },
    ],
    general: [
      { q: 'Tell me about yourself and why you are interested in this role.', difficulty: 'Easy', topic: 'Behavioral', tips: 'Use the Present-Past-Future structure. Keep it under 2 minutes. Connect your background directly to the job.' },
      { q: 'Describe a challenging project you worked on. What was your role and what did you learn?', difficulty: 'Medium', topic: 'Behavioral', tips: 'STAR method: Situation, Task, Action, Result. Quantify impact if possible. Be honest about challenges and growth.' },
      { q: 'Where do you see yourself in 5 years, and how does this role align with that vision?', difficulty: 'Easy', topic: 'Career Goals', tips: 'Show ambition and growth mindset. Align your goals with the company direction. Avoid "in your role" answers.' },
      { q: 'Describe a situation where you had to work with a difficult team member. How did you handle it?', difficulty: 'Medium', topic: 'Teamwork', tips: 'Focus on empathy, communication, and resolution — not blame. Show maturity and conflict-resolution skills.' },
    ],
  },

};

export default DATA;
